### ISSUE TITLE
Release to maven repository

### ISSUE THREAD

**Issue by sawo** [mrburrito/slf4j-aws-lambda#3]
Are you planning to release the project to the maven central repository?

**Comment by mrburrito** [comment]
No. IIRC, Amazon made an update shortly after I started this (or I found a solution) that made it obsolete.  I used these two dependencies in my Gradle file (the AWS version may be a bit outdated) and it solved my logging problem.

```
    runtime 'com.amazonaws:aws-lambda-java-log4j:1.0.0'
    runtime 'org.slf4j:slf4j-log4j12:1.7.12'
```
